Models/ErrorViewModel.cs
using System;

namespace FoodProject.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FoodProject.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/BlogController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FoodProject.Controllers
{
    public class BlogController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/CommentController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FoodProject.Controllers
{
    public class CommentController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FoodProject.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/HomeController.cs
using FoodProject.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace FoodProject.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/MenuController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FoodProject.Controllers
{
    public class MenuController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FoodProject.Controllers
{
    public class ProductController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Views/About/Index.cshtml
<section class="about" id="about">
    <h1 class="heading">Lezzetler<span>Hakkında</span></h1>
    <div class="row">
        <div class="image">
            <img src="~/images/about.jpg" alt="about" />
        </div>
        <div class="content">
            <h3>Burgerlerimizin Gizli Tarifi Nedir?</h3>
            <p>
                Dünya Lezzetleriyle Harmanlanmış, Her Mutfaktan Esinlenerek Özel Soslar Eşliğin Sevgi Ve Emek Katarak Tattığınız Eşsiz Lezzete Ulaşıyoruz.

            </p>
            <p>
                ENG:Special Sauces, Inspired By Every Cuisine, Blended With World Flavors. We Reach The Unique Taste You Taste By Adding Love And Effort.
            </p>
            <p>
                ARP: كل مطبخ ممزوجة مع النكهات العالمية. نصل إلى الذوق الفريد الذي تتذوقه بإضافة الحب والجهد.
            </p>
            <a href="#" class="btn">Başa Dön</a>
        </div>
    </div>
</section>

Views/Blog/Index.cshtml
<section class="blogs" id="blogs">
    <h1 class="heading">Blogumuz <span> </span></h1>
    <div class="box-container">
        <div class="box">
            <div class="image">
                <img src="~/images/blog-1.jpg" alt="blog" />
            </div>
            <div class="content">
                <a href="#" class="title">Burger Nasıl Yapılır? Yazan Şefler / 1 Haziran 2023</a>
                <span> Yazan Şefler /  1 Haz. , 2023</span>
                <p>
                    Ateşte Pişmiş Köftesi, Pufidik Ekmeğinin Arasından Göz Kırpan Hamburgeri Elimize Aldığımız Anın Mutluluğuna Tüm Dünya Gibi Biz De Bağımlıyız.
                </p>
                <a href="#" class="btn">Başa Dön</a>
            </div>
        </div>
        <div class="box">
            <div class="image">
                <img src="~/images/blog-2.jpg" alt="blog" />
            </div>
            <div class="content">
                <a href="#" class="title">Lezzet Sırrı Nedir?</a>
                <span>Yazan Şefler / 15 Haziran, 2023</span>
                <p>
                    Yetenekli Şeflerin Finedining’i Bir Kenara Bırakıp Burgere Dönme Serüvenine Birkaç Yıldır Şahitlik Ediyoruz Ama Ülkemizdeki Iyi Örneklerin Geçmişi Sandığımızdan Daha Köklü. Peki, Tutkunu Olduğumuz Hamburgerin ‘Kusursuz’unun Sırları Neler?
                </p>
                <a href="#" class="btn">Başa Dön</a>
            </div>
        </div>
        <div class="box">
            <div class="image">
                <img src="~/images/blog-3.jpg" alt="blog" />
            </div>
            <div class="content">
                <a href="#" class="title">Sokak Lezzetleri</a>
                <span> Yazan Şefler / 30 Haziran, 2023</span>
                <p>
                    Sokak Lezzetlerinin Yükselişi Hız Kesmiyor Ama Burger Kadar Çok Sevilen, Hemen Her Ülkede, Kültürde Bilinip Kendisine Sağlam Bir Yer Edinen Ortak Bir Tutku Daha Saymak Kolay Değil. Bir Şef Olarak Iki Ülkede Birden Yaşayınca, Bazı Yemek Trendlerini De Iki Farklı Zamanda Tecrübe Edebiliyorsunuz.

                    </p>
                    <a href="#" class="btn">Başa Dön</a>
</div>
        </div>
    </div>
</section>

Views/Comment/Index.cshtml
<section class="review" id="review">
    <h1 class="heading">
        MÜŞTERILERIN DEĞERLENDIRMESI

        <span></span>
    </h1>
    <div class="box-container">
        <div class="box">
            <img src="~/images/quote.png" alt="quote" />
            <p>
                Arkadaşlarımızla Birlikte Öğlen Yemeği Için Gittik. Ortam Çok Güzel, Çalışanlar Çok Ilgili, Yemeklerde Oldukça Lezzetli Idi. Tam Bir Şef Restoranı, Menü Her Ay Değişiyor Ve Yepyeni Lezzetler Tatma Imkanı Buluyorsunuz.
            </p>
            <img src="~/images/userprofile.png" alt="avatar" class="user" />
            <h3>Oğuz Öner</h3>
            <div class="stars">
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star-half-alt"></i>
            </div>
        </div>
        <div class="box">
            <img src="~/images/quote.png" alt="quote" />
            <p>
                Burger Seven Biri Olarak Bu Mekanı Tavsiye Ediyorum. Özellikle Bacon Hamburger Ve Şefin Özel Pizzasını Denemenizi Öneriyorum. Ekmeklerini Kendileri Pişiriyor Ve Çok Hafif. Ayrıca Satın Alabiliyorsunuz. İki Katlı, Temiz Bir Mekan. Fiyatları Aldığınız Hizmete Göre Uygun.
            </p>
            <img src="~/images/userprofile.png" alt="avatar" class="user" />
            <h3>Ekrem İmamoğlu</h3>
            <div class="stars">
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star-half-alt"></i>
            </div>
        </div>
        <div class="box">
            <img src="~/images/quote.png" alt="quote" />
            <p>
                Ailecek Gittik Ve Çok Lezzetli Bir Hamburger Yedik... Gelen Hamburgerler Ve Sunum Gerçekten Süperdi... Hamburger Yemek Için Tereddüt Etmeden Gidilir. Mekan Olarak Da Çok Güzel Bir Yer...
            </p>
            <img src="images/userprofile.png" alt="avatar" class="user" />
            <h3>Kübra Kumbar</h3>
            <div class="stars">
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star-half-alt"></i>
            </div>
        </div>
    </div>
</section>

Views/Contact/Index.cshtml
<section class="contact" id="contact">
    <h1 class="heading"> İletişim <span></span></h1>
    <div class="row">
        <iframe class="map"
                src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d12037.852231349814!2d28.985091699999998!3d41.03700175!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14cab7650656bd63%3A0x8ca058b28c20b6c3!2zVGFrc2ltIE1leWRhbsSxLCBHw7xtw7zFn3N1eXUsIDM0NDM1IEJleW_En2x1L8Swc3RhbmJ1bA!5e0!3m2!1str!2str!4v1652655842555!5m2!1str!2str"
                loading="lazy"
                referrerpolicy="no-referrer-when-downgrade"></iframe>
        <form>
            <h3>İletişim</h3>
            <div class="inputBox">
                <i class="fas fa-user"></i>
                <input type="text" placeholder="isim soyisim" />
            </div>
            <div class="inputBox">
                <i class="fas fa-envelope"></i>
                <input type="email" placeholder="e-mail" />
            </div>
            <div class="inputBox">
                <i class="fas fa-phone"></i>
                <input type="number" placeholder="numara" />
            </div>
            <input type="submit" class="btn" value="contact now" />
        </form>
    </div>
</section>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<!--! header section start  -->

<!--! header section end  -->
<!--! home section start  -->
<section class="home" id="home">
    <div class="content">
        <h3>Hoşgeldiniz</h3>
        <p>
           Dünyaca ünlü şefimizin lezzetleriyle buluşmaya hazır mısınız?
        </p>
        <a href="#" class="btn">Hoşgeldiniz</a>
    </div>
</section>
<!--! home section end  -->
<!--! menu section start  -->
<section class="menu" id="menu">
    <h1 class="heading">Menülerimiz</h1>
    <div class="box-container">
        <div class="box">
            <div class="box-head">
                <img src="~/images/menu-1.png" alt="menu" />
                <span class="menu-category">PIZZA</span>
                <h3>6 Mini Pizza</h3>
                <div class="price">150TL <span>119.99</span></div>
            </div>
       
        </div>
        <div class="box">
            <div class="box-head">
                <img src="~/images/menu-2.png" alt="menu" />
                <span class="menu-category">Burger</span>
                <h3>5 Mini Burger</h3>
                <div class="price">100TL <span>109.99</span></div>
            </div>
     
        </div>
        <div class="box">
            <div class="box-head">
                <img src="~/images/menu-3.png" alt="menu" />
                <span class="menu-category">PIZZA</span>
                <h3>2 Karışık Pizza</h3>
                <div class="price">50TL <span> 59.99</span></div>
            </div>
     
        </div>
  
    </div>
</section>
<!--! menu section end  -->
<!--! products section start  -->
<section class="products" id="products">
    <h1 class="heading">Lezzet Şöleni <span>Menu</span></h1>
    <div class="box-container">
        <div class="box">
            <div class="box-head">
                <span class="title">MINI BURGER</span>
                <a href="#" class="name">Bacon Burger</a>
            </div>
            <div class="image">
                <img src="~/images/product-1.png" alt="" />
            </div>
            <div class="box-bottom">
                <div class="info">
                    <b class="price">89TL</b>
                    <span class="amount">110gr / 300 Cal</span>
                </div>
          
            </div>
        </div>
        <div class="box">
            <div class="box-head">
                <span class="title">MINI BURGER</span>
                <a href="#" class="name">Bacon Burger</a>
            </div>
            <div class="image">
                <img src="~/images/product-2.png" alt="" />
            </div>
            <div class="box-bottom">
                <div class="info">
                    <b class="price">90TL</b>
                    <span class="amount">110gr / 300 Cal</span>
                </div>
       
            </div>
        </div>
        <div class="box dark-bg">
            <div class="box-head">
                <span class="title">MINI BURGER</span>
                <a href="#" class="name">Bacon Burger</a>
            </div>
            <div class="image">
                <img src="~/images/dark-product.jpg" alt="" />
            </div>
            <div class="box-bottom">
                <div class="info">
                    <b class="price">105TL</b>
                    <span class="amount">110gr / 300 Cal</span>
                </div>
           
            </div>
        </div>
    </div>
</section>
<!--! products section end  -->
<!--! about section start  -->
<section class="about" id="about">
    <h1 class="heading">Lezzetler Hakkında </h1>
    <div class="row">
        <div class="image">
            <img src="~/images/about.jpg" alt="about" />
        </div>
        <div class="content">
            <h3>Burgerlerimizin Gizli Tarifi Nedir?</h3>
            <p>
                Dünya lezzetleriyle harmanlanmış, her mutfaktan esinlenerek özel soslar eşliğin
                sevgi ve emek katarak tattığınız eşsiz lezzete ulaşıyoruz.
            </p>
            <p>
                ENG:Special sauces, inspired by every cuisine, blended with world flavors.
                We reach the unique taste you taste by adding love and effort.
            </p>
            <p>
                ARP: كل مطبخ ممزوجة مع النكهات العالمية.
                نصل إلى الذوق الفريد الذي تتذوقه بإضافة الحب والجهد.
            </p>
            <a href="#" class="btn">Başa Dön</a>
        </div>
    </div>
</section>
<!--! about section end  -->
<!--! review section start  -->
<section class="review" id="review">
    <h1 class="heading">Müşterilerin <span>Değerlendirmesi</span></h1>
    <div class="box-container">
        <div class="box">
            <img src="~/images/quote.png" alt="quote" />
            <p>
                Arkadaşlarımızla birlikte öğlen yemeği için gittik. Ortam çok güzel, çalışanlar çok ilgili, yemeklerde oldukça lezzetli idi. Tam bir şef restoranı, menü her ay değişiyor ve yepyeni lezzetler tatma imkanı buluyorsunuz.

              
            </p>
            <img src="~/images/userprofile.png" alt="avatar" class="user" />
            <h3>Elifnaz Sarp</h3>
            <div class="stars">
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star-half-alt"></i>
            </div>
        </div>
        <div class="box">
            <img src="~/images/quote.png" alt="quote" />
            <p>
                Burger seven biri olarak bu mekanı tavsiye ediyorum. Özellikle bacon hamburger ve şefin özel pizzasını denemenizi öneriyorum. Ekmeklerini kendileri pişiriyor ve çok hafif. Ayrıca satın alabiliyorsunuz. İki katlı, temiz bir mekan. Fiyatları aldığınız hizmete göre uygun.


            </p>
            <img src="~/images/userprofile.png" alt="avatar" class="user" />
            <h3>Ekrem İmamoğlu</h3>
            <div class="stars">
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star-half-alt"></i>
            </div>
        </div>
        <div class="box">
            <img src="~/images/quote.png" alt="quote" />
            <p>
                Ailecek gittik ve çok lezzetli bir hamburger yedik... Gelen hamburgerler ve sunum gerçekten süperdi... Hamburger yemek için tereddüt etmeden gidilir. Mekan olarak da çok güzel bir yer...
            </p>
            <img src="~/images/userprofile.png" alt="avatar" class="user" />
            <h3>Kübra Kumbar</h3>
            <div class="stars">
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star-half-alt"></i>
            </div>
        </div>
    </div>
</section>
<!--! review section end  -->
<!--! contact section start  -->
<section class="contact" id="contact">
    <h1 class="heading">iletişim </h1>
    <div class="row">
        <iframe class="map"
                src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d12037.852231349814!2d28.985091699999998!3d41.03700175!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14cab7650656bd63%3A0x8ca058b28c20b6c3!2zVGFrc2ltIE1leWRhbsSxLCBHw7xtw7zFn3N1eXUsIDM0NDM1IEJleW_En2x1L8Swc3RhbmJ1bA!5e0!3m2!1str!2str!4v1652655842555!5m2!1str!2str"
                loading="lazy"
                referrerpolicy="no-referrer-when-downgrade"></iframe>
        <form>
            <h3>get in touch</h3>
            <div class="inputBox">
                <i class="fas fa-user"></i>
                <input type="text" placeholder="isim soyisim" />
            </div>
            <div class="inputBox">
                <i class="fas fa-envelope"></i>
                <input type="email" placeholder="email" />
            </div>
            <div class="inputBox">
                <i class="fas fa-phone"></i>
                <input type="number" placeholder="telefon numarası" />
            </div>
            <input type="submit" class="btn" value="contact now" />
        </form>
    </div>
</section>
<!--! contact section end  -->
<!--! blogs section start  -->
<section class="blogs" id="blogs">
    <h1 class="heading">Blogumuz</h1>
    <div class="box-container">
        <div class="box">
            <div class="image">
                <img src="~/images/blog-1.jpg" alt="blog" />
            </div>
            <div class="content">
                <a href="#" class="title">
                    Burger Nasıl Yapılır?
                    Yazan Şefler / 1 Haziran 2023
                </a>
                <span> / 1 Haz. , 2023</span>
                <p>
                    Ateşte pişmiş köftesi, pufidik ekmeğinin arasından göz kırpan hamburgeri elimize aldığımız anın mutluluğuna tüm dünya gibi biz de bağımlıyız.
                </p>
                <a href="#" class="btn">Başa Dön</a>
            </div>
        </div>
        <div class="box">
            <div class="image">
                <img src="~/images/blog-2.jpg" alt="blog" />
            </div>
            <div class="content">
                <a href="#" class="title">Lezzet sırrı nedir?</a>
                <span>Yazan Şefler / 15 Haziran, 2023</span>
                <p>
                    Yetenekli şeflerin finedining’i bir kenara bırakıp burgere dönme serüvenine birkaç yıldır şahitlik ediyoruz ama ülkemizdeki iyi örneklerin geçmişi sandığımızdan daha köklü. Peki, tutkunu olduğumuz hamburgerin ‘kusursuz’unun sırları neler?
                </p>
                <a href="#" class="btn">Başa Dön</a>
            </div>
        </div>
        <div class="box">
            <div class="image">
                <img src="~/images/blog-3.jpg" alt="blog" />
            </div>
            <div class="content">
                <a href="#" class="title">Sokak Lezzetleri</a>
                <span>Yazan Şefler / 30 Haziran, 2023</span>
                <p>
                    Sokak lezzetlerinin yükselişi hız kesmiyor ama burger kadar çok sevilen, hemen her ülkede, kültürde bilinip kendisine sağlam bir yer edinen ortak bir tutku daha saymak kolay değil. Bir şef olarak iki ülkede birden yaşayınca, bazı yemek trendlerini de iki farklı zamanda tecrübe edebiliyorsunuz.
                </p>
                <a href="#" class="btn">Başa Dön</a>
            </div>
        </div>
    </div>
</section>

Views/Menu/Index.cshtml
 
 <section class="menu" id="menu">
    <h1 class="heading">our <span>Menü</span></h1>
    <div class="box-container">
        <div class="box">
            <div class="box-head">
                <img src="~/images/menu-1.png" alt="menu" />
                <span class="menu-category">PIZZA</span>
                <h3>6 Mini Pizza </h3>
                <div class="price">90TL <span>119.99</span></div>
            </div>

        </div>
        <div class="box">
            <div class="box-head">
                <img src="~/images/menu-2.png" alt="menu" />
                <span class="menu-category">Burger</span>
                <h3>5 Mini Burger</h3>
                <div class="price">100TL <span>119</span></div>
            </div>

        </div>
        <div class="box">
            <div class="box-head">
                <img src="~/images/menu-3.png" alt="menu" />
                <span class="menu-category">Pizza</span>
                <h3>2 Karışık Pizza</h3>
                <div class="price">100TL <span>119</span></div>
            </div>

        </div>
    </div>
</section>

Views/Product/Index.cshtml
<section class="products" id="products">
    <h1 class="heading">
        LEZZET ŞÖLENI MENU

        <span></span>
    </h1>
    <div class="box-container">
        <div class="box">
            <div class="box-head">
                <span class="title">MINI BURGER</span>
                <a href="#" class="name">Bacon Burger</a>
            </div>
            <div class="image">
                <img src="~/images/product-1.png" alt="" />
            </div>
            <div class="box-bottom">
                <div class="info">
                    <b class="price">89TL</b>
                    <span class="amount">110gr / 300 Cal</span>
                </div>
             
            </div>
        </div>
        <div class="box">
            <div class="box-head">
                <span class="title">MINI BURGER</span>
                <a href="#" class="name">Bacon Burger</a>
            </div>
            <div class="image">
                <img src="~/images/product-2.png" alt="" />
            </div>
            <div class="box-bottom">
                <div class="info">
                    <b class="price">90TL</b>
                    <span class="amount">110gr / 300 Cal</span>
                </div>
               
            </div>
        </div>
        <div class="box dark-bg">
            <div class="box-head">
                <span class="title">MINI BURGER</span>
                <a href="#" class="name">Bacon Burger</a>
            </div>
            <div class="image">
                <img src="~/images/dark-product.jpg" alt="" />
            </div>
            <div class="box-bottom">
                <div class="info">
                    <b class="price">120TL</b>
                    <span class="amount">110gr / 300 Cal</span>
                </div>
           
            </div>
        </div>
    </div>
</section>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html lang="en">
 
<meta http-equiv="content-type" content="text/html;charset=UTF-8" /> 
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
   
    <title>Food Project</title>
    <link rel="stylesheet" href="~/css/style.css" />
</head>
<body>

    <header class="header">
        <a href="@Url.Action("Index","Home")" class="logo">
            <img src="~/images/logo.png" alt="logo" />
        </a>
        <nav class="navbar">
            <a href="@Url.Action("Index","Home")" class="active">Anasayfa</a>
            <a href="@Url.Action("Index","About")">Hakkımızda</a>
            <a href="@Url.Action("Index","Menu")">Menü</a>
            <a href="@Url.Action("Index","Product")">Ürünler</a>
            <a href="@Url.Action("Index","Comment")">Yorumlar</a>
            <a href="@Url.Action("Index","Contact")">İletişim</a>
            <a href="@Url.Action("Index","Blog")">Blog</a>
        </nav>

        <div class="buttons">
            <button id="search-btn">
                <i class="fas fa-search"></i>
            </button>

            <button id="menu-btn">
                <i class="fas fa-bars"></i>
            </button>
        </div>

        <div class="search-form">
            <input type="text"
                   class="search-input"
                   id="search-box"
                   placeholder="search here" />
            <i class="fas fa-search"></i>
        </div>

        <div class="cart-items-container">
            <div class="cart-item">
                <i class="fas fa-times"></i>
                <img src="~/images/menu-1.png" alt="menu" />
                <div class="content">
                    <h3>cart item 01</h3>
                    <div class="price">$15.99/-</div>
                </div>
            </div>
            <div class="cart-item">
                <i class="fas fa-times"></i>
                <img src="~/images/menu-2.png" alt="menu" />
                <div class="content">
                    <h3>cart item 02</h3>
                    <div class="price">$15.99/-</div>
                </div>
            </div>
            <div class="cart-item">
                <i class="fas fa-times"></i>
                <img src="~/images/menu-3.png" alt="menu" />
                <div class="content">
                    <h3>cart item 03</h3>
                    <div class="price">$15.99/-</div>
                </div>
            </div>
            <div class="cart-item">
                <i class="fas fa-times"></i>
                <img src="~/images/menu-4.png" alt="menu" />
                <div class="content">
                    <h3>cart item 04</h3>
                    <div class="price">$15.99/-</div>
                </div>
            </div>
            <a href="#" class="btn">checkout now</a>
        </div>
    </header>
    @RenderBody()

    <section class="footer">
        <div class="search">
            <input type="text" class="search-input" placeholder="Search" />
            <button class="btn btn-primary">search</button>
        </div>
        <div class="share">
            <a href="#" class="fab fa-facebook"></a>
            <a href="#" class="fab fa-twitter"></a>
            <a href="#" class="fab fa-instagram"></a>
            <a href="#" class="fab fa-linkedin"></a>
            <a href="#" class="fab fa-pinterest"></a>
        </div>

        <div class="links">
            <a href="@Url.Action("Index","Home")" class="active">Anasayfa</a>
            <a href="@Url.Action("Index","About")">Hakkımızda</a>
            <a href="@Url.Action("Index","Menu")">Menü</a>
            <a href="@Url.Action("Index","Product")">Ürünler</a>
            <a href="@Url.Action("Index","Comment")">Yorumlar</a>
            <a href="@Url.Action("Index","Contact")">İletişim</a>
            <a href="@Url.Action("Index","Blog")">Blog</a>
        </div>

        <div class="credit">
            Tasarımcı <span>Elifnaz Sarp</span> | Tüm hakları saklıdır.
        </div>
    </section>

    <script src="~/js/script.js"></script>
    <script src="https://kit.fontawesome.com/278627476d.js" crossorigin="anonymous"></script>

</body>
 
</html>